version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:80"

  json-server:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: ["npx", "json-server", "--watch", "data/mockdata.json", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
